@startuml
actor Attore 
participant Command
participant Logic 

Attore -> Command: sendRequest()
Command <- Logic: showItems()
Par 
    Command <- Logic: releaseItem()
    Command -> Logic: takeItems()
end
Alt Oggetto presente 
    Command <- Logic: addItem()
else Oggetto non presente
    Command <- Logic: changeRoom()
end
Critical Stato aggiornato 
Attore <- Command: updateStateGame()
else Stato non aggiornato
Attore <- Command: showError()
end
@enduml